import os
import csv
from datetime import datetime


def make_score_bar(score):
    filled_count = round(score / 10)
    filled_count = max(0, min(10, filled_count))
    empty_count = 10 - filled_count
    bar = "#" * filled_count + "-" * empty_count
    return f"[{bar}] {score}%"


def format_analysis_report(resume_snippet, job_snippet, analysis_dict, timestamp):
    score = analysis_dict.get("match_score", 0)
    score_bar = make_score_bar(score)

    def format_list(items, prefix="  * "):
        if not items:
            return f"{prefix}None identified\n"
        return "\n".join(f"{prefix}{item}" for item in items) + "\n"

    def format_numbered(items):
        if not items:
            return "  No suggestions available.\n"
        return "\n".join(f"  {i+1}. {item}" for i, item in enumerate(items)) + "\n"

    report = f"""
{'=' * 60}
           RESUMATCH — ANALYSIS REPORT
{'=' * 60}

Generated: {timestamp}

{'-' * 60}
  INPUT SUMMARY
{'-' * 60}
  Resume Preview : {resume_snippet}...
  JD Preview     : {job_snippet}...

{'-' * 60}
  MATCH SCORE
{'-' * 60}
  Score: {score}/100
  {score_bar}

  {analysis_dict.get('score_explanation', 'N/A')}

{'-' * 60}
  OVERALL VERDICT
{'-' * 60}
  {analysis_dict.get('overall_verdict', 'N/A')}

{'-' * 60}
  MATCHED SKILLS (found in your resume)
{'-' * 60}
{format_list(analysis_dict.get('matched_skills', []), '  [Y] ')}
{'-' * 60}
  MISSING SKILLS (not found in your resume)
{'-' * 60}
{format_list(analysis_dict.get('missing_skills', []), '  [X] ')}
{'-' * 60}
  REQUIRED TECHNICAL SKILLS
{'-' * 60}
{format_list(analysis_dict.get('required_technical_skills', []))}
{'-' * 60}
  REQUIRED SOFT SKILLS
{'-' * 60}
{format_list(analysis_dict.get('required_soft_skills', []))}
{'-' * 60}
  STRONGEST RESUME SECTIONS
{'-' * 60}
{format_list(analysis_dict.get('strongest_sections', []), '  * ')}
{'-' * 60}
  TOP 3 IMPROVEMENT SUGGESTIONS
{'-' * 60}
{format_numbered(analysis_dict.get('improvement_suggestions', []))}
{'=' * 60}
  End of Report — Generated by ResuMatch
{'=' * 60}
"""
    return report


def save_report(report_text, topic_hint, reports_folder="reports"):
    os.makedirs(reports_folder, exist_ok=True)

    now = datetime.now()
    filename = f"analysis_{now.strftime('%Y-%m-%d_%H-%M-%S')}.txt"
    filepath = os.path.join(reports_folder, filename)

    try:
        with open(filepath, "w", encoding="utf-8") as report_file:
            report_file.write(report_text)

        absolute_path = os.path.abspath(filepath)
        print(f"\nReport saved to: {absolute_path}")
        return filename

    except IOError as error:
        print(f"Could not save report file: {error}")
        return None


def save_to_history(analysis_dict, timestamp, history_folder="history"):
    os.makedirs(history_folder, exist_ok=True)

    csv_path = os.path.join(history_folder, "history_log.csv")
    file_exists = os.path.exists(csv_path)

    try:
        with open(csv_path, "a", newline="", encoding="utf-8") as csv_file:
            writer = csv.writer(csv_file)

            if not file_exists:
                writer.writerow([
                    "timestamp",
                    "match_score",
                    "missing_skills_count",
                    "matched_skills_count"
                ])

            writer.writerow([
                timestamp,
                analysis_dict.get("match_score", 0),
                len(analysis_dict.get("missing_skills", [])),
                len(analysis_dict.get("matched_skills", []))
            ])

        print(f"Analysis recorded in history log.")

    except IOError as error:
        print(f"Could not save to history: {error}")


def display_results_in_terminal(analysis_dict, quick_tip):
    score = analysis_dict.get("match_score", 0)
    score_bar = make_score_bar(score)

    print("\n")
    print("=" * 60)
    print("           RESUMATCH ANALYSIS RESULTS")
    print("=" * 60)

    print("\n  MATCH SCORE")
    print("  " + "-" * 40)
    print(f"  Score: {score}/100")
    print(f"  {score_bar}")
    print()

    print(f"  {analysis_dict.get('score_explanation', 'N/A')}")
    print()

    print("  OVERALL VERDICT")
    print("  " + "-" * 40)
    print(f"  {analysis_dict.get('overall_verdict', 'N/A')}")
    print()

    print("  MATCHED SKILLS (in your resume)")
    print("  " + "-" * 40)
    matched = analysis_dict.get("matched_skills", [])
    if matched:
        for skill in matched:
            print(f"    [Y] {skill}")
    else:
        print("    No matched skills identified.")
    print()

    print("  MISSING SKILLS (not in your resume)")
    print("  " + "-" * 40)
    missing = analysis_dict.get("missing_skills", [])
    if missing:
        for skill in missing:
            print(f"    [X] {skill}")
    else:
        print("    No missing skills — great job!")
    print()

    print("  REQUIRED TECHNICAL SKILLS")
    print("  " + "-" * 40)
    tech_skills = analysis_dict.get("required_technical_skills", [])
    if tech_skills:
        for skill in tech_skills:
            print(f"    * {skill}")
    else:
        print("    None identified.")
    print()

    print("  REQUIRED SOFT SKILLS")
    print("  " + "-" * 40)
    soft_skills = analysis_dict.get("required_soft_skills", [])
    if soft_skills:
        for skill in soft_skills:
            print(f"    * {skill}")
    else:
        print("    None identified.")
    print()

    print("  STRONGEST RESUME SECTIONS")
    print("  " + "-" * 40)
    strong = analysis_dict.get("strongest_sections", [])
    if strong:
        for section in strong:
            print(f"    * {section}")
    else:
        print("    Not identified.")
    print()

    print("  TOP 3 IMPROVEMENT SUGGESTIONS")
    print("  " + "-" * 40)
    suggestions = analysis_dict.get("improvement_suggestions", [])
    if suggestions:
        for i, suggestion in enumerate(suggestions, start=1):
            print(f"    {i}. {suggestion}")
            print()
    else:
        print("    No suggestions available.")
    print()

    print("  QUICK TIP — Most Important Skill to Learn Next")
    print("  " + "-" * 40)
    print(f"  {quick_tip}")
    print()

    print("=" * 60)
    print("           End of Analysis")
    print("=" * 60)
    print()
